import { defineConfig } from "tsup";
export default defineConfig({
  splitting: true,
  sourcemap: true,
  // minify: true,
  clean: true,
  // cjsInterop: true,
  treeshake: true,

  external: [
    "framer-motion",
    "@nextui-org/react",
    "@monaco-editor/react",
    "@rjsf/core",
    "@rjsf/utils",
    "@rjsf/validator-ajv8",
    "@tremor/react",
    "axios",
    "bignumber.js",
    "dataloader",
    "dexie",
    "next",
    "next-auth",
    "react",
    "react-dev-inspector",
    "react-dom",
    "react-draggable",
    "react-hot-toast",
    "lodash-es",
    "bignumber.js",
    "lucide-react",
  ],
  entry: {
    index: "index.ts",
    metrics: "metrics.ts",
    form: "form.ts",
    plugins: "plugins.ts",
    ui: "ui.ts",
    dev: "dev.ts",
    inspector: "inspector.ts",
    jsontable: "jsontable.ts",
    experimental: "experimental.ts",
    aiem: "aiem.ts",
  },
});
